import json
import shutil
import glob
import os

# Create the target directory safely
os.makedirs("public/images/case_studies/one_more_time", exist_ok=True)

quotes = [
    {"author": "Sample Producer", "text": "The foundation of 'One More Time' is a brilliant example of micro-sampling. Daft Punk took tiny snippets of Eddie Johns' obscure disco record, pitched them up, and rearranged them to create an entirely new, euphoric chord progression."},
    {"author": "Dance Music Historian", "text": "The Roland TR-909 drum machine defines house music. Its punchy, synthetic analog kick drum and crisp hi-hats provided the exact driving energy needed to propel the disco sample into a modern club context."},
    {"author": "Vocal Engineer", "text": "This track popularized the extreme use of Antares Auto-Tune as a creative effect rather than a corrective tool. By setting the retune speed to zero, Romanthony's soulful vocal was transformed into a hybrid robot instrument."},
    {"author": "Analog Enthusiast", "text": "Instead of clean digital effects, French House producers often ran samples through analog guitar pedals like the Electro-Harmonix Small Stone phaser to give the loop a swirling, dynamic movement that constantly evolved."},
    {"author": "Mixing Engineer", "text": "Sidechain compression is the most defining characteristic of the 'French Touch' genre. By routing the kick drum to compress the sample and bass line, the entire track forcefully rhythmically pumps and breathes with the beat."},
    {"author": "Keyboard Historian", "text": "While the track prominently features strings, they aren't generated by a Mellotron or an orchestra. They are inherent elements of the original 1970s Eddie Johns sample, chopped and looped along with the brass and bass."},
    {"author": "Synth Specialist", "text": "Daft Punk's 'Discovery' era was heavily reliant on hardware synthesizers. Classics like the Roland Juno-106 added warmth, grit, and massive analog texture that software synths of the early 2000s still struggled to perfectly emulate."},
    {"author": "Spatial Audio Expert", "text": "Dance music thrives on energy and width. Elements like the sweeping phaser and the heavily processed vocals were deliberately mixed incredibly wide in the stereo field to create an immersive, surrounding experience on club systems."},
    {"author": "Rhythm Programmer", "text": "Unlike funk or rock where human timing fluctuations create the groove, the relentless, hypnotic energy of house music relies on the rigid mathematical precision of a sequenced four-on-the-floor beat."},
    {"author": "Mastering Engineer", "text": "A massive, narrow parametric EQ spike at 16kHz would ruin the track, making it harsh and painful. Instead, mastering dance music requires careful top-end balancing to ensure it sounds loud and exciting without piercing the listener's ears."},
    {"author": "DJ/Producer", "text": "Filter sweeps are foundational to this era. Sweeping a low-pass filter to gradually muffle a looping sample creates intense tension, which is then triumphantly released when the filter opens back up for the chorus."},
    {"author": "Session Bassist", "text": "The bass line in 'One More Time' is characterized by its electronic precision and ability to lock perfectly with the kick drum, pointing to the use of synthesizers or heavily processed samples rather than a live Fender bass performance."},
    {"author": "Music Critic", "text": "Daft Punk essentially codified the 'French Filter House' genre with this track. It combines the joyous, celebratory aesthetic of 1970s disco with the aggressive, driving production techniques of modern electronic dance music."},
    {"author": "Studio Technician", "text": "A tremolo effect simply modulates volume at a fixed rate. The pumping effect in this track is achieved via sidechain compression, which is entirely crucial because it specifically reacts dynamically to the rhythm of the kick drum hitting."},
    {"author": "Acoustic Consultant", "text": "In modern dance music production, the low frequencies are precious real estate. Producers carefully carve out EQ space, cutting the low-end from samples and synths so the kick and sub-bass can hit smoothly and powerfully without muddy competition."},
    {"author": "Audio Editor", "text": "Advanced polyphonic tuning software like Melodyne DNA didn't exist in 2000. The iconic, glitchy vocal effect was definitively achieved using the original, faster-than-light retune speed settings of Antares Auto-Tune."},
    {"author": "Mix Architect", "text": "The stereo field is a powerful compositional tool. By keeping the kick drum anchored strictly in the center and pushing the swirling synth pads and vocal delays extremely wide, it creates a massive, three-dimensional sonic contrast."},
    {"author": "Sampling Pioneer", "text": "While modern digital time-stretching algorithms preserve transients perfectly without changing pitch, early samplers shifted pitch and time simultaneously. This 'flaw' heavily colored the grit and texture of early 2000s sample-based music."},
    {"author": "Hardware Collector", "text": "The tactile, hands-on workflow of classic samplers—like the Akai MPC or E-Mu SP-1200—was integral to the creative process of classic house. Producers would chop the vinyl physically onto pads and perform the new arrangement by hand."},
    {"author": "Orchestral Arranger", "text": "The magic of 'One More Time' lies in its sample repurposing. Daft Punk didn't need to hire an entire orchestra at Air Studios; their genius was extracting the essence of 1970s disco strings directly from a forgotten vinyl groove."}
]

image_keys = [
    "sample_chop", "tr909", "autotune", "phaser_pedal", "sidechain",
    "mellotron", "hardware_synth", "stereo_field", "sequencer", "eq_spike",
    "filter_sweep", "jazz_bass", "french_house", "tremolo_pedal", "eq_separation",
    "melodyne", "stereo_width", "vp9000", "sp1200", "air_studios"
]

artifacts_dir = "/Users/thorhouse/.gemini/antigravity/brain/70f85d8d-d4b6-4c31-be22-dfeed0f7406b"
image_paths = []

for i, key in enumerate(image_keys):
    q_num = i + 1
    files = glob.glob(f"{artifacts_dir}/omt_q{q_num}_{key}_*.png")
    if files:
        latest_file = sorted(files)[-1]
        dest_filename = f"omt_q{q_num}_{key}.png"
        dest_path = f"public/images/case_studies/one_more_time/{dest_filename}"
        shutil.copy(latest_file, dest_path)
        image_paths.append(f"/images/case_studies/one_more_time/{dest_filename}")
        print(f"Copied image {q_num}")
    else:
        # Should not happen
        image_paths.append("")
        print(f"Error: No image found for Q{q_num}")

filepath = 'src/data/course_data.json'
with open(filepath, 'r') as f:
    data = json.load(f)

for section in data.get('sections', []):
    if section.get('title') == 'Stage 5: Case Studies':
        for quiz in section.get('items', []):
            if "'One More Time'" in quiz.get('title', ''):
                for i, q in enumerate(quiz.get('questions', [])):
                    if i < 20:
                        q['expert_quote'] = quotes[i]
                        if image_paths[i]:
                            q['img'] = image_paths[i]

with open(filepath, 'w') as f:
    json.dump(data, f, indent=4)

print("Injected One More Time successfully.")
