
import json

updates = {
    "v1_p6_t16_b_1": [
        { "text": "The difference (in dB) between the quietest audible sound (Noise Floor) and the loudest possible sound (Clipping Point)", "is_true": "yes" },
        { "text": "The difference (in Hz) between the lowest bass frequency and the highest treble frequency the speaker can play", "is_true": "no" },
        { "text": "The physical distance between the microphone and the sound source during the recording process", "is_true": "no" },
        { "text": "The amount of time it takes for a reverb tail to decay from its maximum volume to silence", "is_true": "no" }
    ],
    "v1_p6_t16_b_2": [
        { "text": "The inherent hiss/hum generated by the equipment itself (preamps, cables, converters) even when no music is playing", "is_true": "yes" },
        { "text": "The background noise caused by environmental factors like traffic, air conditioning, or computer fans", "is_true": "no" },
        { "text": "The distortion added to the signal when the input gain is turned up too high on the preamp", "is_true": "no" },
        { "text": "The sound of the music leaking from the headphones into the microphone during recording", "is_true": "no" }
    ],
    "v1_p6_t16_b_3": [
        { "text": "96 dB (calculated as 16 bits multiplied by 6dB per bit)", "is_true": "yes" },
        { "text": "144 dB (typical for 24-bit high resolution audio)", "is_true": "no" },
        { "text": "60 dB (typical for analog cassette tape recorders)", "is_true": "no" },
        { "text": "120 dB (the threshold of pain for human hearing)", "is_true": "no" }
    ],
    "v1_p6_t16_b_4": [
        { "text": "To trade 'Quantization Distortion' (nasty grit) for 'Broadband Hiss' (pleasant/ignorable)", "is_true": "yes" },
        { "text": "To artificially increase the bit depth of the file to improve the audio quality", "is_true": "no" },
        { "text": "To add a subtle analog harmonic saturation effect that warms up digital recordings", "is_true": "no" },
        { "text": "To remove the background noise floor from the recording by phasing it out", "is_true": "no" }
    ],
    "v1_p6_t16_b_5": [
        { "text": "Noise Gate / Expander", "is_true": "yes" },
        { "text": "Compressor / Limiter", "is_true": "no" },
        { "text": "Equalizer / Filter", "is_true": "no" },
        { "text": "Reverb / Delay", "is_true": "no" }
    ],
    "v1_p6_t16_b_6": [
        { "text": "High SNR is better (The signal is much louder than the noise)", "is_true": "yes" },
        { "text": "Low SNR is better (The noise floor is masked by the signal)", "is_true": "no" },
        { "text": "Ideally they should be Equal (0dB SNR) for perfect balance", "is_true": "no" },
        { "text": "It depends entirely on the genre of music being recorded", "is_true": "no" }
    ],
    "v1_p6_t16_b_7": [
        { "text": "Ambient Room Noise (Traffic, Computer Fans, Air Con) - typically around 30-40dB SPL", "is_true": "yes" },
        { "text": "The inherent thermal noise of the microphone preamp - typically around -120dBu", "is_true": "no" },
        { "text": "Electronic interference from standard instrument cables - typically negligible", "is_true": "no" },
        { "text": "Digital quantization noise from the A/D converter - typically below -140dB", "is_true": "no" }
    ],
    "v1_p6_t16_b_8": [
        { "text": "To smoothly lower the noise floor to silence, avoiding a sudden 'click' or 'drop' in room tone when the region ends", "is_true": "yes" },
        { "text": "To ensure the file size is minimized by removing silence from the end of the audio clip", "is_true": "no" },
        { "text": "To change the pitch of the final note creates a pleasing aesthetic effect for the listener", "is_true": "no" },
        { "text": "It is not technically necessary in modern DAWs as they automatically handle region boundaries", "is_true": "no" }
    ],
    "v1_p6_t16_b_9": [
        { "text": "24-bit (-144dB floor)", "is_true": "yes" },
        { "text": "16-bit (-96dB floor)", "is_true": "no" },
        { "text": "8-bit (-48dB floor)", "is_true": "no" },
        { "text": "12-bit (-72dB floor)", "is_true": "no" }
    ],
    "v1_p6_t16_b_10": [
        { "text": "The mismatch between the smooth analog voltage and the nearest available digital 'snapshot' value", "is_true": "yes" },
        { "text": "Interference from poor quality cables that allows radio frequencies to leak into the signal", "is_true": "no" },
        { "text": "Recording at too high a level, causing the signal to exceed 0dBFS and clip", "is_true": "no" },
        { "text": "Using a sample rate that is too low to capture the high frequencies accurately", "is_true": "no" }
    ],
    "v1_p6_t16_i_1": [
        { "text": "6 dB (approx)", "is_true": "yes" },
        { "text": "1 dB (approx)", "is_true": "no" },
        { "text": "10 dB (approx)", "is_true": "no" },
        { "text": "3 dB (approx)", "is_true": "no" }
    ],
    "v1_p6_t16_i_2": [
        { "text": "No, it actually INCREASES the total noise energy, but moves it to frequencies we can't hear well", "is_true": "yes" },
        { "text": "Yes, it significantly LOWERS the total noise energy across the entire frequency spectrum", "is_true": "no" },
        { "text": "It keeps the total energy the same but spreads it evenly like white noise", "is_true": "no" },
        { "text": "It completely eliminates the noise by using phase cancellation algorithms", "is_true": "no" }
    ],
    "v1_p6_t16_i_3": [
        { "text": "Compression lowers loud peaks (Gain Reduction) but Makeup Gain turns EVERYTHING up, including the quiet hiss", "is_true": "yes" },
        { "text": "Compressors inherently generate electrical hum due to the nature of their internal circuitry", "is_true": "no" },
        { "text": "The reduction of dynamic range causes the digital bits to be used less efficiently", "is_true": "no" },
        { "text": "It doesn't; compressors actually lower the noise floor by pushing quiet sounds down", "is_true": "no" }
    ],
    "v1_p6_t16_i_4": [
        { "text": "Technically yes (they decode to PCM), but the 'Data compression' artifacts introduce noise and warbling at low bitrates", "is_true": "yes" },
        { "text": "No, MP3s inherently limit the maximum volume of the file to save data space", "is_true": "no" },
        { "text": "Yes, and they often have better dynamic range because they remove inaudible sounds", "is_true": "no" },
        { "text": "No, MP3s are strictly 8-bit files and therefore have a very high noise floor", "is_true": "no" }
    ],
    "v1_p6_t16_i_5": [
        { "text": "Approx -130 dBV (depending on impedance/bandwidth)", "is_true": "yes" },
        { "text": "Approx -96 dBV (Equivalent to 16-bit audio)", "is_true": "no" },
        { "text": "Approx -144 dBV (Equivalent to 24-bit audio)", "is_true": "no" },
        { "text": "0 dBV (There is no physical limit to silence)", "is_true": "no" }
    ],
    "v1_p6_t16_i_6": [
        { "text": "A Gate mutes fully (hard cut). An Expander gently pushes quiet sounds down further (soft attenuation), sounding more natural", "is_true": "yes" },
        { "text": "An Expander makes quiet sounds louder, whereas a Gate makes them quieter", "is_true": "no" },
        { "text": "A Gate is used for vocals only, whereas an Expander is used for drums only", "is_true": "no" },
        { "text": "There is no difference; they are two names for the exactly same process", "is_true": "no" }
    ],
    "v1_p6_t16_i_7": [
        { "text": "High impedance signals are weak current sources, making them easily overpowered by electrostatic interference (buzz)", "is_true": "yes" },
        { "text": "High impedance cables act as low-pass filters, removing the high frequencies where noise lives", "is_true": "no" },
        { "text": "They are typically unbalanced, meaning they don't have a ground shield to protect the signal", "is_true": "no" },
        { "text": "The high resistance of the cable generates significant thermal noise compared to low-Z cables", "is_true": "no" }
    ],
    "v1_p6_t16_i_8": [
        { "text": "Truncation Distortion: The bottom 8 bits are just chopped off, causing gritty, correlated noise on reverb tails", "is_true": "yes" },
        { "text": "The file simply becomes quieter because the volume information in the lower bits is lost", "is_true": "no" },
        { "text": "Nothing audible happens unless you turn the volume up to dangerous levels", "is_true": "no" },
        { "text": "The file size remains the same, but the audio quality drops to 8-bit equivalent", "is_true": "no" }
    ],
    "v1_p6_t16_i_9": [
        { "text": "50Hz (UK/EU) vs 60Hz (USA) - matching the AC Mains frequency", "is_true": "yes" },
        { "text": "100Hz (UK/EU) vs 120Hz (USA) - double the mains frequency", "is_true": "no" },
        { "text": "Fixed at 1kHz regardless of the region or power supply", "is_true": "no" },
        { "text": "Random white noise that covers the entire spectrum", "is_true": "no" }
    ],
    "v1_p6_t16_i_10": [
        { "text": "Technically yes (thermal resistance), but they have no active electronics to generate hiss, so they are considered very quiet", "is_true": "yes" },
        { "text": "Yes, they are notoriously noisy because of the heavy moving coil mechanism", "is_true": "no" },
        { "text": "No, dynamic microphones are passive devices and therefore generate absolutely zero noise", "is_true": "no" },
        { "text": "Only when Phantom Power is accidentally engaged, which causes them to hum", "is_true": "no" }
    ],
    "v1_p6_t16_a_1": [
        { "text": "RPDF eliminates distortion but modulates the noise floor (noise pumps with signal). TPDF has a constant steady noise floor", "is_true": "yes" },
        { "text": "RPDF adds significant harmonic distortion, whereas TPDF is perfectly transparent", "is_true": "no" },
        { "text": "TPDF uses less CPU power to generate than RPDF, making it better for real-time use", "is_true": "no" },
        { "text": "There is no audible difference; the preference is purely theoretical", "is_true": "no" }
    ],
    "v1_p6_t16_a_2": [
        { "text": "Often yes, because steeper linear-phase anti-aliasing filters (required for ultra-low noise) incur more processing delay", "is_true": "yes" },
        { "text": "No, higher quality converters typically have faster processors and lower latency", "is_true": "no" },
        { "text": "Latency is determined solely by the buffer size setting in the DAW, not the converter", "is_true": "no" },
        { "text": "Yes, but only because they operate at much higher sample rates by default", "is_true": "no" }
    ],
    "v1_p6_t16_a_3": [
        { "text": "It doesn't directly. Sample Rate dictates Frequency response (Bandwidth). Bit Depth dictates Dynamic Range", "is_true": "yes" },
        { "text": "Higher Sample Rate always equals higher Dynamic Range because there are more samples per second", "is_true": "no" },
        { "text": "Lower Sample Rate equals higher Dynamic Range because each sample can be larger", "is_true": "no" },
        { "text": "They are exactly the same thing; increasing one automatically increases the other", "is_true": "no" }
    ],
    "v1_p6_t16_a_4": [
        { "text": "The noise floor rises dramatically, and quantization error becomes correlated to the signal, creating a 'fizzing' distortion", "is_true": "yes" },
        { "text": "The signal becomes mono and loses all stereo width information immediately", "is_true": "no" },
        { "text": "The pitch of the audio drops significantly, creating a slow-down effect", "is_true": "no" },
        { "text": "The high frequencies are filtered out, making the sound muffled and dark", "is_true": "no" }
    ],
    "v1_p6_t16_a_5": [
        { "text": "Narrowband / Tonal Noise (It occupies a specific frequency)", "is_true": "yes" },
        { "text": "Broadband Noise (It covers the entire frequency spectrum evenly)", "is_true": "no" },
        { "text": "Pink Noise (It has equal energy per octave like music)", "is_true": "no" },
        { "text": "Impulse Noise (It consists of short, random clicks and pops)", "is_true": "no" }
    ],
    "v1_p6_t16_a_6": [
        { "text": "It makes loud sounds louder (or quiet sounds quieter), effectively stretching the distance between peaks and floor", "is_true": "yes" },
        { "text": "It compresses the dynamic range by bringing the quiet sounds up to meet the loud ones", "is_true": "no" },
        { "text": "It adds artificial noise to the recording to simulate a higher noise floor", "is_true": "no" },
        { "text": "It keeps the level constant but changes the EQ curve dynamically", "is_true": "no" }
    ],
    "v1_p6_t16_a_7": [
        { "text": "Magnetic particles are randomly distributed. This randomness creates a physical 'grain' noise (hiss) when read by the head", "is_true": "yes" },
        { "text": "The motors used to spin the tape reels created mechanical noise that leaked into the signal", "is_true": "no" },
        { "text": "Analog circuitry was simply not advanced enough to produce quiet components back then", "is_true": "no" },
        { "text": "Static electricity built up on the tape surface causing constant crackling", "is_true": "no" }
    ],
    "v1_p6_t16_a_8": [
        { "text": "Compansion: It boosted highs during recording (to sit above the hiss) and cut them back during playback (taking the hiss down with them)", "is_true": "yes" },
        { "text": "It used a specialized notch filter to remove the specific frequency of the tape hiss", "is_true": "no" },
        { "text": "It used digital noise removal algorithms to subtract the noise profile from the audio", "is_true": "no" },
        { "text": "It physically slowed the tape down during quiet passages to reduce friction noise", "is_true": "no" }
    ],
    "v1_p6_t16_a_9": [
        { "text": "It spreads the quantization noise energy over a wider bandwidth (e.g. up to 88kHz), lowering the noise density in the audible band", "is_true": "yes" },
        { "text": "It significantly increases the overall noise floor, making the recording sound hissier", "is_true": "no" },
        { "text": "It has no effect on noise; oversampling is purely for improving frequency response", "is_true": "no" },
        { "text": "It introduces aliasing distortion which adds anharmonic noise to the signal", "is_true": "no" }
    ],
    "v1_p6_t16_a_10": [
        { "text": "It takes a 'Noise Profile' (fingerprint) of the silence, then mathematically subtracts those specific frequencies from the audio", "is_true": "yes" },
        { "text": "It uses a fast-acting Noise Gate to silence the audio whenever the volume drops", "is_true": "no" },
        { "text": "It aggressively filters out all high frequencies where the noise is most prominent", "is_true": "no" },
        { "text": "It inverts the phase of the left channel to cancel out the noise in the center", "is_true": "no" }
    ],
    "v1_p6_t16_m_1": [
        { "text": "Because the analog front-end thermal noise swamps the lowest 3-4 bits. The theoretical quietness of 24-bit is louder than physics allows", "is_true": "yes" },
        { "text": "Because 24-bit ADCs are partially defective by design and cannot reach full spec", "is_true": "no" },
        { "text": "Because of clock jitter errors that randomize the least significant bits", "is_true": "no" },
        { "text": "Because the operating system driver truncates the data to 20 bits automatically", "is_true": "no" }
    ],
    "v1_p6_t16_m_2": [
        { "text": "Massive Oversampling (e.g. 64x) combined with steep Noise Shaping to push quantization noise way into the MHz range", "is_true": "yes" },
        { "text": "By using extremely high voltage rails (+/- 100V) to maximize the signal-to-noise ratio", "is_true": "no" },
        { "text": "By using 32 separate 1-bit converters in parallel to average out the noise", "is_true": "no" },
        { "text": "They don't; 1-bit converters are inherently noisy and low fidelity", "is_true": "no" }
    ],
    "v1_p6_t16_m_3": [
        { "text": "23 bits for audio (Mantissa), 8 bits for exponent, 1 for sign. Effectively 24-bit precision that slides up and down in volume", "is_true": "yes" },
        { "text": "32 bits for audio, giving a fixed dynamic range of 192dB without any scaling", "is_true": "no" },
        { "text": "16 bits for audio and 16 bits for exponent, offering a balance of precision and range", "is_true": "no" },
        { "text": "The allocation changes dynamically depending on the volume of the signal", "is_true": "no" }
    ],
    "v1_p6_t16_m_4": [
        { "text": "It creates 'Sidebands' (ghost frequencies) either side of a loud tone, reducing detail and widening the stereo image incorrectly", "is_true": "yes" },
        { "text": "It raises the broadband noise floor evenly across the entire frequency spectrum", "is_true": "no" },
        { "text": "It causes random digital clicks and pops similar to a vinyl record scratching", "is_true": "no" },
        { "text": "It introduces a constant low-frequency hum related to the sample rate", "is_true": "no" }
    ],
    "v1_p6_t16_m_5": [
        { "text": "Aliasing: Ultrasonic frequencies fold back into the audible spectrum as dissonant noise", "is_true": "yes" },
        { "text": "Loss of bass frequencies due to the phase shift of the decimation filter", "is_true": "no" },
        { "text": "Increased clock jitter causing the stereo image to become blurred", "is_true": "no" },
        { "text": "Quantization distortion due to wordlength reduction without proper dither", "is_true": "no" }
    ],
    "v1_p6_t16_m_6": [
        { "text": "Functionally yes (below noise floor), but mathematically no. True identity is -Infinity dB (Digital Silence)", "is_true": "yes" },
        { "text": "Yes, absolutely perfectly identical down to the very last bit", "is_true": "no" },
        { "text": "No, they are massively different and would sound completely distinct", "is_true": "no" },
        { "text": "It depends on the volume you listen at; louder playback reveals more differences", "is_true": "no" }
    ],
    "v1_p6_t16_m_7": [
        { "text": "It needs to be just loud enough to randomize the transition between the lowest bit states (0 and 1)", "is_true": "yes" },
        { "text": "It needs to be loud enough to be clearly audible over the music to work effectively", "is_true": "no" },
        { "text": "to ensure it covers up any analog tape hiss that might be present in the recording", "is_true": "no" },
        { "text": "It is an arbitrary value chosen by software developers with no mathematical basis", "is_true": "no" }
    ],
    "v1_p6_t16_m_8": [
        { "text": "A specialized noise-shaping algorithm curve designed to be invisible to the human ear, often used in final mastering", "is_true": "yes" },
        { "text": "A high-intensity dither used for aggressive genres like Rock and Metal", "is_true": "no" },
        { "text": "A rectangular dither that uses power functions to eliminate distortion completely", "is_true": "no" },
        { "text": "A dither that is only applied during the power-down sequence of the DAW", "is_true": "no" }
    ],
    "v1_p6_t16_m_9": [
        { "text": "It remains 60dB (Signal and Noise both went up). However, Dynamic Range might resultantly decrease if you hit the ceiling", "is_true": "yes" },
        { "text": "It improves to 80dB because the signal is now significantly louder than before", "is_true": "no" },
        { "text": "It drops to 40dB because amplifying noise makes it more annoying", "is_true": "no" },
        { "text": "It doubles to 120dB due to the logarithmic nature of decibels", "is_true": "no" }
    ],
    "v1_p6_t16_m_10": [
        { "text": "To prevent clicks caused by the waveform instantly jumping from a high voltage value to silence (a step impulse)", "is_true": "yes" },
        { "text": "Because it is the only point where the edit can be performed without losing sync", "is_true": "no" },
        { "text": "It looks neater on the screen when the waveforms align perfectly with the grid", "is_true": "no" },
        { "text": "To ensure that the file size is kept to a minimum by removing excess data", "is_true": "no" }
    ]
}

import json
filepath = '/Users/thorhouse/Edexcel_MT_Revision/mtg-web-app/src/data/dictionary_quizzes.json'

with open(filepath, 'r') as f:
    data = json.load(f)

# Update Logic
count = 0
for vol in data['volumes']:
    if vol['id'] == 'vol1':
        for part in vol['parts']:
            if part['id'] == 'p6':
                for topic in part['topics']:
                    for level, questions in topic['levels'].items():
                        for q in questions:
                            if q['id'] in updates:
                                q['answers'] = updates[q['id']]
                                count += 1

print(f"Updated {count} questions for Topic 16")

with open(filepath, 'w') as f:
    json.dump(data, f, indent=4)
